// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['handlers']['App']['Bootstrap']();
}

export function CancelImport() {
  return window['go']['handlers']['App']['CancelImport']();
}

export function CatalogAlphabet() {
  return window['go']['handlers']['App']['CatalogAlphabet']();
}

export function ClearCoverCache() {
  return window['go']['handlers']['App']['ClearCoverCache']();
}

export function ClearSearchHistory() {
  return window['go']['handlers']['App']['ClearSearchHistory']();
}

export function CoverWarmupPreview() {
  return window['go']['handlers']['App']['CoverWarmupPreview']();
}

export function CoverWarmupProgress() {
  return window['go']['handlers']['App']['CoverWarmupProgress']();
}

export function DismissWindowClose() {
  return window['go']['handlers']['App']['DismissWindowClose']();
}

export function GetAnnotation(arg1) {
  return window['go']['handlers']['App']['GetAnnotation'](arg1);
}

export function GetAuthor(arg1) {
  return window['go']['handlers']['App']['GetAuthor'](arg1);
}

export function GetGenre(arg1) {
  return window['go']['handlers']['App']['GetGenre'](arg1);
}

export function GetSeries(arg1) {
  return window['go']['handlers']['App']['GetSeries'](arg1);
}

export function GetWork(arg1) {
  return window['go']['handlers']['App']['GetWork'](arg1);
}

export function GetWorkDetails(arg1) {
  return window['go']['handlers']['App']['GetWorkDetails'](arg1);
}

export function LastImportReport() {
  return window['go']['handlers']['App']['LastImportReport']();
}

export function ListAuthors(arg1) {
  return window['go']['handlers']['App']['ListAuthors'](arg1);
}

export function ListGenres(arg1) {
  return window['go']['handlers']['App']['ListGenres'](arg1);
}

export function ListSeries(arg1) {
  return window['go']['handlers']['App']['ListSeries'](arg1);
}

export function ListWorks(arg1) {
  return window['go']['handlers']['App']['ListWorks'](arg1);
}

export function OpenDataDir() {
  return window['go']['handlers']['App']['OpenDataDir']();
}

export function OpenLogsDir() {
  return window['go']['handlers']['App']['OpenLogsDir']();
}

export function PreviewImport() {
  return window['go']['handlers']['App']['PreviewImport']();
}

export function RandomWork() {
  return window['go']['handlers']['App']['RandomWork']();
}

export function RecordSearch(arg1) {
  return window['go']['handlers']['App']['RecordSearch'](arg1);
}

export function RecordViewed(arg1) {
  return window['go']['handlers']['App']['RecordViewed'](arg1);
}

export function RetryStartup() {
  return window['go']['handlers']['App']['RetryStartup']();
}

export function SearchCatalog(arg1) {
  return window['go']['handlers']['App']['SearchCatalog'](arg1);
}

export function SearchHistory() {
  return window['go']['handlers']['App']['SearchHistory']();
}

export function SelectINPXFile(arg1) {
  return window['go']['handlers']['App']['SelectINPXFile'](arg1);
}

export function SelectLibraryRoot(arg1) {
  return window['go']['handlers']['App']['SelectLibraryRoot'](arg1);
}

export function SetCatalogView(arg1) {
  return window['go']['handlers']['App']['SetCatalogView'](arg1);
}

export function SetINPXPath(arg1) {
  return window['go']['handlers']['App']['SetINPXPath'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['handlers']['App']['SetLocale'](arg1);
}

export function SetSidebarCollapsed(arg1) {
  return window['go']['handlers']['App']['SetSidebarCollapsed'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['handlers']['App']['SetTheme'](arg1);
}

export function SetVisualEffects(arg1) {
  return window['go']['handlers']['App']['SetVisualEffects'](arg1);
}

export function StartCoverWarmup() {
  return window['go']['handlers']['App']['StartCoverWarmup']();
}

export function StartImport() {
  return window['go']['handlers']['App']['StartImport']();
}

export function StopCoverWarmup() {
  return window['go']['handlers']['App']['StopCoverWarmup']();
}
