// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['handlers']['App']['Bootstrap']();
}

export function OpenDataDir() {
  return window['go']['handlers']['App']['OpenDataDir']();
}

export function OpenLogsDir() {
  return window['go']['handlers']['App']['OpenLogsDir']();
}

export function RetryStartup() {
  return window['go']['handlers']['App']['RetryStartup']();
}

export function SetLocale(arg1) {
  return window['go']['handlers']['App']['SetLocale'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['handlers']['App']['SetTheme'](arg1);
}

export function SetVisualEffects(arg1) {
  return window['go']['handlers']['App']['SetVisualEffects'](arg1);
}
