// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {inpximport} from '../models';

export function Bootstrap():Promise<app.Bootstrap>;

export function CancelImport():Promise<void>;

export function DismissWindowClose():Promise<void>;

export function LastImportReport():Promise<inpximport.ReportDTO>;

export function OpenDataDir():Promise<void>;

export function OpenLogsDir():Promise<void>;

export function PreviewImport():Promise<app.ImportPreview>;

export function RetryStartup():Promise<app.Bootstrap>;

export function SelectLibraryRoot(arg1:string):Promise<string>;

export function SetLocale(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetVisualEffects(arg1:string):Promise<void>;

export function StartImport():Promise<inpximport.ReportDTO>;
