// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['handlers']['App']['Bootstrap']();
}

export function BuildIssueReport(arg1, arg2) {
  return window['go']['handlers']['App']['BuildIssueReport'](arg1, arg2);
}

export function CancelFileOp(arg1, arg2) {
  return window['go']['handlers']['App']['CancelFileOp'](arg1, arg2);
}

export function CancelImport() {
  return window['go']['handlers']['App']['CancelImport']();
}

export function CatalogAlphabet() {
  return window['go']['handlers']['App']['CatalogAlphabet']();
}

export function CheckStorage(arg1) {
  return window['go']['handlers']['App']['CheckStorage'](arg1);
}

export function ClearCoverCache() {
  return window['go']['handlers']['App']['ClearCoverCache']();
}

export function ClearReaderPath() {
  return window['go']['handlers']['App']['ClearReaderPath']();
}

export function ClearSearchHistory() {
  return window['go']['handlers']['App']['ClearSearchHistory']();
}

export function CoverWarmupPreview() {
  return window['go']['handlers']['App']['CoverWarmupPreview']();
}

export function CoverWarmupProgress() {
  return window['go']['handlers']['App']['CoverWarmupProgress']();
}

export function CreateCatalogBackup() {
  return window['go']['handlers']['App']['CreateCatalogBackup']();
}

export function DatabaseMaintenanceRunning() {
  return window['go']['handlers']['App']['DatabaseMaintenanceRunning']();
}

export function DeleteSecret(arg1) {
  return window['go']['handlers']['App']['DeleteSecret'](arg1);
}

export function Diagnostics() {
  return window['go']['handlers']['App']['Diagnostics']();
}

export function DismissDumpOffer() {
  return window['go']['handlers']['App']['DismissDumpOffer']();
}

export function DismissWindowClose() {
  return window['go']['handlers']['App']['DismissWindowClose']();
}

export function DownloadEdition(arg1) {
  return window['go']['handlers']['App']['DownloadEdition'](arg1);
}

export function ExportPersonal(arg1) {
  return window['go']['handlers']['App']['ExportPersonal'](arg1);
}

export function GetAnnotation(arg1) {
  return window['go']['handlers']['App']['GetAnnotation'](arg1);
}

export function GetAuthor(arg1) {
  return window['go']['handlers']['App']['GetAuthor'](arg1);
}

export function GetGenre(arg1) {
  return window['go']['handlers']['App']['GetGenre'](arg1);
}

export function GetHome() {
  return window['go']['handlers']['App']['GetHome']();
}

export function GetSeries(arg1) {
  return window['go']['handlers']['App']['GetSeries'](arg1);
}

export function GetWork(arg1) {
  return window['go']['handlers']['App']['GetWork'](arg1);
}

export function GetWorkDetails(arg1) {
  return window['go']['handlers']['App']['GetWorkDetails'](arg1);
}

export function ImportPersonal(arg1) {
  return window['go']['handlers']['App']['ImportPersonal'](arg1);
}

export function LastImportReport() {
  return window['go']['handlers']['App']['LastImportReport']();
}

export function ListAuthors(arg1) {
  return window['go']['handlers']['App']['ListAuthors'](arg1);
}

export function ListGenres(arg1) {
  return window['go']['handlers']['App']['ListGenres'](arg1);
}

export function ListSeries(arg1) {
  return window['go']['handlers']['App']['ListSeries'](arg1);
}

export function ListWorks(arg1) {
  return window['go']['handlers']['App']['ListWorks'](arg1);
}

export function OpenDataDir() {
  return window['go']['handlers']['App']['OpenDataDir']();
}

export function OpenDownloadsDir() {
  return window['go']['handlers']['App']['OpenDownloadsDir']();
}

export function OpenLogsDir() {
  return window['go']['handlers']['App']['OpenLogsDir']();
}

export function OptimizeDatabase() {
  return window['go']['handlers']['App']['OptimizeDatabase']();
}

export function PersonalSnapshot() {
  return window['go']['handlers']['App']['PersonalSnapshot']();
}

export function PreviewImport() {
  return window['go']['handlers']['App']['PreviewImport']();
}

export function PreviewPersonalImport(arg1) {
  return window['go']['handlers']['App']['PreviewPersonalImport'](arg1);
}

export function RandomWork() {
  return window['go']['handlers']['App']['RandomWork']();
}

export function ReadEdition(arg1) {
  return window['go']['handlers']['App']['ReadEdition'](arg1);
}

export function ReaderPath() {
  return window['go']['handlers']['App']['ReaderPath']();
}

export function RecordSearch(arg1) {
  return window['go']['handlers']['App']['RecordSearch'](arg1);
}

export function RecordViewed(arg1) {
  return window['go']['handlers']['App']['RecordViewed'](arg1);
}

export function RetryStartup() {
  return window['go']['handlers']['App']['RetryStartup']();
}

export function SaveDiagnosticArchive(arg1) {
  return window['go']['handlers']['App']['SaveDiagnosticArchive'](arg1);
}

export function SaveIssueReport(arg1, arg2) {
  return window['go']['handlers']['App']['SaveIssueReport'](arg1, arg2);
}

export function SearchCatalog(arg1) {
  return window['go']['handlers']['App']['SearchCatalog'](arg1);
}

export function SearchHistory() {
  return window['go']['handlers']['App']['SearchHistory']();
}

export function SecretStatus(arg1) {
  return window['go']['handlers']['App']['SecretStatus'](arg1);
}

export function SelectDownloadsDir(arg1) {
  return window['go']['handlers']['App']['SelectDownloadsDir'](arg1);
}

export function SelectINPXFile(arg1) {
  return window['go']['handlers']['App']['SelectINPXFile'](arg1);
}

export function SelectLibraryRoot(arg1) {
  return window['go']['handlers']['App']['SelectLibraryRoot'](arg1);
}

export function SelectPersonalExportPath(arg1) {
  return window['go']['handlers']['App']['SelectPersonalExportPath'](arg1);
}

export function SelectPersonalImportPath(arg1) {
  return window['go']['handlers']['App']['SelectPersonalImportPath'](arg1);
}

export function SelectReaderPath(arg1) {
  return window['go']['handlers']['App']['SelectReaderPath'](arg1);
}

export function SetAIProvider(arg1) {
  return window['go']['handlers']['App']['SetAIProvider'](arg1);
}

export function SetCatalogView(arg1) {
  return window['go']['handlers']['App']['SetCatalogView'](arg1);
}

export function SetINPXPath(arg1) {
  return window['go']['handlers']['App']['SetINPXPath'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['handlers']['App']['SetLocale'](arg1);
}

export function SetSecret(arg1, arg2) {
  return window['go']['handlers']['App']['SetSecret'](arg1, arg2);
}

export function SetSidebarCollapsed(arg1) {
  return window['go']['handlers']['App']['SetSidebarCollapsed'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['handlers']['App']['SetTheme'](arg1);
}

export function SetVisualEffects(arg1) {
  return window['go']['handlers']['App']['SetVisualEffects'](arg1);
}

export function SetWorkComment(arg1, arg2) {
  return window['go']['handlers']['App']['SetWorkComment'](arg1, arg2);
}

export function SetWorkRating(arg1, arg2) {
  return window['go']['handlers']['App']['SetWorkRating'](arg1, arg2);
}

export function SetWorkWantToRead(arg1, arg2) {
  return window['go']['handlers']['App']['SetWorkWantToRead'](arg1, arg2);
}

export function ShowInFolder(arg1) {
  return window['go']['handlers']['App']['ShowInFolder'](arg1);
}

export function StartCoverWarmup() {
  return window['go']['handlers']['App']['StartCoverWarmup']();
}

export function StartImport() {
  return window['go']['handlers']['App']['StartImport']();
}

export function StopCoverWarmup() {
  return window['go']['handlers']['App']['StopCoverWarmup']();
}
