// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {storage} from '../models';
import {covers} from '../models';
import {downloads} from '../models';
import {catalog} from '../models';
import {inpximport} from '../models';

export function Bootstrap():Promise<app.Bootstrap>;

export function CancelFileOp(arg1:number,arg2:string):Promise<void>;

export function CancelImport():Promise<void>;

export function CatalogAlphabet():Promise<Array<string>>;

export function CheckStorage(arg1:boolean):Promise<storage.Snapshot>;

export function ClearCoverCache():Promise<void>;

export function ClearReaderPath():Promise<void>;

export function ClearSearchHistory():Promise<void>;

export function CoverWarmupPreview():Promise<number>;

export function CoverWarmupProgress():Promise<covers.Progress>;

export function DismissDumpOffer():Promise<void>;

export function DismissWindowClose():Promise<void>;

export function DownloadEdition(arg1:number):Promise<downloads.Result>;

export function GetAnnotation(arg1:number):Promise<covers.Annotation>;

export function GetAuthor(arg1:number):Promise<catalog.Author>;

export function GetGenre(arg1:number):Promise<catalog.Genre>;

export function GetSeries(arg1:number):Promise<catalog.Series>;

export function GetWork(arg1:number):Promise<catalog.Work>;

export function GetWorkDetails(arg1:number):Promise<catalog.WorkDetails>;

export function LastImportReport():Promise<inpximport.ReportDTO>;

export function ListAuthors(arg1:catalog.ListPeopleQuery):Promise<catalog.AuthorPage>;

export function ListGenres(arg1:string):Promise<Array<catalog.Genre>>;

export function ListSeries(arg1:catalog.ListPeopleQuery):Promise<catalog.SeriesPage>;

export function ListWorks(arg1:catalog.ListWorksQuery):Promise<catalog.WorkPage>;

export function OpenDataDir():Promise<void>;

export function OpenDownloadsDir():Promise<void>;

export function OpenLogsDir():Promise<void>;

export function PreviewImport():Promise<app.ImportPreview>;

export function RandomWork():Promise<catalog.Work>;

export function ReadEdition(arg1:number):Promise<downloads.Result>;

export function ReaderPath():Promise<string>;

export function RecordSearch(arg1:string):Promise<void>;

export function RecordViewed(arg1:number):Promise<void>;

export function RetryStartup():Promise<app.Bootstrap>;

export function SearchCatalog(arg1:catalog.SearchQuery):Promise<catalog.SearchResult>;

export function SearchHistory():Promise<Array<string>>;

export function SelectDownloadsDir(arg1:string):Promise<string>;

export function SelectINPXFile(arg1:string):Promise<string>;

export function SelectLibraryRoot(arg1:string):Promise<string>;

export function SelectReaderPath(arg1:string):Promise<string>;

export function SetCatalogView(arg1:string):Promise<void>;

export function SetINPXPath(arg1:string):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function SetSidebarCollapsed(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetVisualEffects(arg1:string):Promise<void>;

export function ShowInFolder(arg1:string):Promise<void>;

export function StartCoverWarmup():Promise<void>;

export function StartImport():Promise<inpximport.ReportDTO>;

export function StopCoverWarmup():Promise<void>;
